apiVersion: v1
kind: Secret
metadata:
  name: sa-token-secret # Nombre que usaste antes, mantengámoslo
  namespace: devops-tools
  annotations:
    kubernetes.io/service-account.name: jenkins-admin # Vincula este secret a la ServiceAccount
type: kubernetes.io/service-account-token
