apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ChristianAcostaMz/example_argocd.git
    targetRevision: HEAD
    path: apps/monitoring
    directory:
      recurse: true  # 👈 Esto habilita el escaneo recursivo
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
