helmCharts:
  - name: prometheus
    repo: https://prometheus-community.github.io/helm-charts
    version: 25.21.0
    releaseName: prometheus
    namespace: monitoring
    valuesFile: prometheus-values.yaml
