adminUser: admin
adminPassword: changeme

service:
  type: LoadBalancer

persistence:
  enabled: false

dashboards:
  default:
    argo-cd:
      gnetId: 14584
      revision: 1
      datasource: Prometheus

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true

