# gitlab-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8929
      targetPort: 8929
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gitlab
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.0.15  # IP de tu tarro con GitLab
    ports:
      - port: 8929
